<?php
$json_path = 'python/instagram_cookies.txt';
$content = file_get_contents($json_path);

// Check if it's already JSON
if (strpos($content, '[') === 0) {
    $cookies = json_decode($content, true);
    if ($cookies) {
        $out = "# Netscape HTTP Cookie File\n";
        $out .= "# This file is generated by Crevix Cookie Bridge.\n\n";
        
        foreach($cookies as $c) {
            $domain = $c['domain'] ?? '';
            $flag = (strpos($domain, '.') === 0) ? 'TRUE' : 'FALSE';
            $path = $c['path'] ?? '/';
            $secure = ($c['secure'] ?? true) ? 'TRUE' : 'FALSE';
            $expiry = isset($c['expirationDate']) ? (int)$c['expirationDate'] : 0;
            $name = $c['name'] ?? '';
            $value = $c['value'] ?? '';
            
            if ($name && $domain) {
                $out .= "$domain\t$flag\t$path\t$secure\t$expiry\t$name\t$value\n";
            }
        }
        file_put_contents($json_path, $out);
        echo "Successfully converted JSON to Netscape format.\n";
    } else {
        echo "Error: Invalid JSON data.\n";
    }
} else {
    echo "Cookies already in Netscape format or unknown.\n";
}
?>
