<?php
require 'db.php';
require 'includes/header.php';

if (!isset($_SESSION['user_id'])) { header("Location: login.php"); exit(); }

$message = '';

if ($_SERVER['REQUEST_METHOD'] == 'POST') {
    $title = $conn->real_escape_string(trim($_POST['title']));
    $desc = $conn->real_escape_string(trim($_POST['description']));
    $category = $conn->real_escape_string($_POST['category']);
    $user_id = $_SESSION['user_id'];

    if (isset($_FILES['media_file']) && $_FILES['media_file']['error'] == 0) {
        $file = $_FILES['media_file'];
        $filename = time() . '_' . preg_replace('/[^a-zA-Z0-9._-]/', '', basename($file['name']));
        $target_dir = "uploads/media/";
        $target_file = $target_dir . $filename;

        $ext = strtolower(pathinfo($target_file, PATHINFO_EXTENSION));
        $type = in_array($ext, ['mp4','webm','ogg','mov','avi']) ? 'video' : 'photo';

        // Handle thumbnail
        $thumb_path = '';
        if (isset($_POST['thumbnail_data']) && !empty($_POST['thumbnail_data'])) {
            $thumb_data = $_POST['thumbnail_data'];
            $thumb_data = str_replace('data:image/png;base64,', '', $thumb_data);
            $thumb_data = str_replace(' ', '+', $thumb_data);
            $thumb_decoded = base64_decode($thumb_data);
            $thumb_name = 'thumb_' . time() . '.png';
            $thumb_path = 'uploads/media/' . $thumb_name;
            file_put_contents($thumb_path, $thumb_decoded);
        }

        if (move_uploaded_file($file['tmp_name'], $target_file)) {
            $sql = "INSERT INTO media (user_id, title, description, file_path, thumbnail, type, category) VALUES ('$user_id', '$title', '$desc', '$target_file', '$thumb_path', '$type', '$category')";
            if ($conn->query($sql)) {
                $message = "<div class='alert alert-success'>✅ Upload successful! <a href='dashboard.php' style='color:var(--gold)'>View in Dashboard</a></div>";
            } else {
                $message = "<div class='alert alert-error'>Database error: " . $conn->error . "</div>";
            }
        } else {
            $message = "<div class='alert alert-error'>Failed to move uploaded file.</div>";
        }
    } else {
        $message = "<div class='alert alert-error'>Please select a file.</div>";
    }
}
?>

<div style="max-width:700px; margin:40px auto;">
    <h2 style="color:var(--gold); margin-bottom:6px;">⬆️ Upload Media</h2>
    <p style="color:var(--muted); margin-bottom:30px;">Share your videos and photos with the world.</p>
    <?php echo $message; ?>

    <form method="POST" enctype="multipart/form-data" id="uploadForm">
        <!-- DROP ZONE -->
        <div class="drop-zone" id="dropZone">
            <div class="icon">📁</div>
            <p>Drag & drop your file here or <strong style="color:var(--gold)">click to browse</strong></p>
            <input type="file" name="media_file" id="fileInput" accept="video/*,image/*" required style="display:none;">
        </div>

        <!-- AUTO THUMBNAIL PREVIEW (generated by JS from video) -->
        <img id="thumbPreview" class="thumb-preview" alt="Auto-generated thumbnail">
        <canvas id="thumbCanvas" style="display:none;"></canvas>
        <input type="hidden" name="thumbnail_data" id="thumbnailData">

        <div class="input-group">
            <label>Title</label>
            <input type="text" name="title" required placeholder="Give your content a title">
        </div>
        <div class="input-group">
            <label>Description</label>
            <textarea name="description" rows="4" placeholder="Describe your content..."></textarea>
        </div>
        <div class="input-group">
            <label>Category</label>
            <select name="category">
                <option value="General">General</option>
                <option value="Music">Music</option>
                <option value="Gaming">Gaming</option>
                <option value="Education">Education</option>
                <option value="Vlog">Vlog</option>
                <option value="Art">Art</option>
                <option value="Tech">Tech</option>
                <option value="Photography">Photography</option>
                <option value="Film">Film</option>
            </select>
        </div>
        <button type="submit" class="btn-primary" style="width:100%; padding:14px; font-size:1rem;">🚀 Publish</button>
    </form>
</div>

<script>
// Drag & Drop + File Select
const dropZone = document.getElementById('dropZone');
const fileInput = document.getElementById('fileInput');
const thumbPreview = document.getElementById('thumbPreview');
const thumbCanvas = document.getElementById('thumbCanvas');
const thumbnailData = document.getElementById('thumbnailData');

dropZone.addEventListener('click', () => fileInput.click());
dropZone.addEventListener('dragover', (e) => { e.preventDefault(); dropZone.classList.add('dragover'); });
dropZone.addEventListener('dragleave', () => dropZone.classList.remove('dragover'));
dropZone.addEventListener('drop', (e) => {
    e.preventDefault();
    dropZone.classList.remove('dragover');
    fileInput.files = e.dataTransfer.files;
    handleFile(e.dataTransfer.files[0]);
});
fileInput.addEventListener('change', () => { if(fileInput.files[0]) handleFile(fileInput.files[0]); });

function handleFile(file) {
    dropZone.innerHTML = '<p style="color:var(--gold); font-weight:600;">✅ ' + file.name + ' (' + (file.size/1024/1024).toFixed(2) + ' MB)</p>';

    // Auto-generate thumbnail from video
    if (file.type.startsWith('video/')) {
        const video = document.createElement('video');
        video.preload = 'metadata';
        video.muted = true;
        video.playsInline = true;

        video.addEventListener('loadeddata', function() {
            // Seek to 2 seconds for a better frame
            video.currentTime = Math.min(2, video.duration * 0.25);
        });

        video.addEventListener('seeked', function() {
            thumbCanvas.width = video.videoWidth;
            thumbCanvas.height = video.videoHeight;
            const ctx = thumbCanvas.getContext('2d');
            ctx.drawImage(video, 0, 0, thumbCanvas.width, thumbCanvas.height);
            const dataURL = thumbCanvas.toDataURL('image/png');
            thumbPreview.src = dataURL;
            thumbPreview.classList.add('show');
            thumbnailData.value = dataURL;
            URL.revokeObjectURL(video.src);
        });

        video.src = URL.createObjectURL(file);
    } else if (file.type.startsWith('image/')) {
        // For images, use the image itself as thumbnail
        const reader = new FileReader();
        reader.onload = function(e) {
            thumbPreview.src = e.target.result;
            thumbPreview.classList.add('show');
            thumbnailData.value = e.target.result;
        };
        reader.readAsDataURL(file);
    }
}
</script>

<?php require 'includes/footer.php'; ?>
